apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  labels:
    app: static
spec:
  replicas: 2
  selector:
    matchLabels:
      app:static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: nginx
        image: image1:v1
        ports:
        - containerPort: 80
---apiVersion: v1
kind: Service
metadata:
  name: static-clusterip
spec:
  type: ClusterIP
  selector:
    app: static
  ports:
    - port: 8080
      targetPort: 80
